openapi: 3.0.0
info:
  title: IUG_FINDER_API
  version: "1.0.0"
  description: IUG Finder API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3000

tags:
  - name: IUG Finder
    description: API

paths:
  /api/auth/login:
    post:
      tags:
        - IUG Finder
      summary: User Login
      description: Login for an existing user
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: test@iugfinder.com
                password:
                  type: string
                  example: password123#
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Login successful
                  user:
                    type: object
                    properties:
                      username:
                        type: string
                        example: exampleuser
        '401':
          description: Invalid credentials
